name: Python package

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

jobs:
  build:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     python-version: [2.7, 3.5, 3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      # - name: Set up Python ${{ matrix.python-version }}
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          # python-version: ${{ matrix.python-version }}
          python-version: "3.8"
          architecture: "x64"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
      - name: Test with pytest
        run: |
          pytest
